column.list.paraclique = c("b_1999", "b_2000", 
                           "averagesmoke1996to2000", "percent2004diabetes",
                           "ageadjustedpercent2004diabetes", "percentobesity2004", 
                           "ageadjustedpercentobesity2004", 
                           "percentleisuretimephysicalinactivityprevalence2004",
                           "ageadjustedpercentleisuretimephysicalinactivityprevalence2004", "PH_SODA")

column.list.pca = c("educationHighSchoolOrAboveRate", 
                    "ageadjustedpercentleisuretimephysicalinactivityprevalence2004", 
                    "percentleisuretimephysicalinactivityprevalence2004", 
                    "perCapitaIncome", 
                    "medianHouseholdIncome2000", 
                    "peopleInPovertyRate", 
                    "ageadjustedpercentobesity2004", 
                    "perCapitaPersonalIncome", 
                    "percentobesity2004", 
                    "sampleMedianHousingUnitValue", 
                    "AvgDailyMaxAirTemperatureF", 
                    "AvgDailyMinAirTemperatureF", 
                    "AvgDailyMaxHeatIndexF", 
                    "unemploymentRate", 
                    "AvgDayLandSurfaceTemperatureF", 
                    "AvgDailyPrecipitationmm", 
                    "AvgFineParticulateMatterµgm", 
                    "populationPerSquareMile", 
                    "percent2004diabetes", 
                    "populationMedianAgeApril2000", 
                    "ageadjustedpercent2004diabetes",
                    "fastFoodRestaurantsPer1000",
                    "fullServiceRestaurantsPer1000")

column.list.pca.subset.1 = c("sampleMedianHousingUnitValue", 
                             "unemploymentRate", 
                             "populationPerSquareMile")

column.list.pca.subset.2 = c("educationHighSchoolOrAboveRate", 
                             "ageadjustedpercentleisuretimephysicalinactivityprevalence2004", 
                             "percentleisuretimephysicalinactivityprevalence2004", 
                             "perCapitaIncome", 
                             "medianHouseholdIncome2000", 
                             "peopleInPovertyRate", 
                             "ageadjustedpercentobesity2004", 
                             "perCapitaPersonalIncome", 
                             "percentobesity2004", 
                             "AvgDailyMaxAirTemperatureF", 
                             "AvgDailyMinAirTemperatureF", 
                             "AvgDailyMaxHeatIndexF", 
                             "AvgDayLandSurfaceTemperatureF", 
                             "AvgDailyPrecipitationmm", 
                             "AvgFineParticulateMatterµgm", 
                             "percent2004diabetes", 
                             "populationMedianAgeApril2000", 
                             "ageadjustedpercent2004diabetes",
                             "fastFoodRestaurantsPer1000",
                             "fullServiceRestaurantsPer1000")

column.list.pca.5tiles = c("5tile.educationHighSchoolOrAboveRate", 
                           "5tile.ageadjustedpercentleisuretimephysicalinactivityprevalence2004", 
                           "5tile.percentleisuretimephysicalinactivityprevalence2004", 
                           "5tile.perCapitaIncome", 
                           "5tile.medianHouseholdIncome2000", 
                           "5tile.peopleInPovertyRate", 
                           "5tile.ageadjustedpercentobesity2004", 
                           "5tile.perCapitaPersonalIncome", 
                           "5tile.percentobesity2004", 
                           "5tile.sampleMedianHousingUnitValue", 
                           "5tile.AvgDailyMaxAirTemperatureF", 
                           "5tile.AvgDailyMinAirTemperatureF", 
                           "5tile.AvgDailyMaxHeatIndexF", 
                           "5tile.unemploymentRate", 
                           "5tile.AvgDayLandSurfaceTemperatureF", 
                           "5tile.AvgDailyPrecipitationmm", 
                           "5tile.AvgFineParticulateMatterµgm", 
                           "5tile.populationPerSquareMile", 
                           "5tile.percent2004diabetes", 
                           "5tile.populationMedianAgeApril2000", 
                           "5tile.ageadjustedpercent2004diabetes",
                           "5tile.fastFoodRestaurantsPer1000",
                           "5tile.fullServiceRestaurantsPer1000")
